language: scala
scala:
  - 2.9.2
  - 2.9.1
jdk:
  - openjdk7
  - oraclejdk7

env:
  - PLAY_VERSION=2.1.1

before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 

script: play-${PLAY_VERSION}/play test

notifications:
email: false
